# Generated by Django 3.0.8 on 2020-10-08 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kawasaki', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='kawasaki',
            name='model',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='kawasaki',
            name='price',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='kawasaki',
            name='image',
            field=models.FileField(upload_to='images/kawasaki/'),
        ),
    ]
